set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR x86)

set(CROSS_PATH "$ENV{HOME}/.local/opt/cross/bin")

set(CMAKE_C_COMPILER ${CROSS_PATH}/i686-elf-gcc)
set(CMAKE_CXX_COMPILER ${CROSS_PATH}/i686-elf-g++)
set(CMAKE_LINKER ${CROSS_PATH}/i686-elf-ld)
set(CMAKE_ASM_NASM_COMPILER nasm)
set(CMAKE_ASM_NASM_OBJECT_FORMAT elf32)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
